In [1]:
!pip install transformers
#!pip install pytorch_lightning
!pip install sentencepiece datasets seqeval
!pip install wandb
#!curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
#!sudo apt-get install git-lfs
#!conda install -y pytorch torchvision torchaudio pytorch-cuda=11.0 -c pytorch -c nvidia
#!conda install -y pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 38.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 56.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.4/182.4 KB 5.2 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 18.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 452.9/452.9 KB 46.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 KB 5.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.0/132.0 KB 18.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 213.0/213.0 KB 26.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 KB 19.0 MB/s eta 0:00:00
  Created wheel for seqeval: filename=s

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
task = "ner" # Should be one of "ner", "pos" or "chunk"
model_checkpoint = "bert-base-cased"
batch_size = 16

In [4]:
#from huggingface_hub import notebook_login
#notebook_login()

In [5]:
import wandb
wandb.init(project="Bachelor_Thesis", entity="maxhager28", name="Token_classification_jnlpb_weak_50")

ERROR:wandb.jupyter:Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.


<IPython.core.display.Javascript object>

wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc


In [6]:
from datasets import load_dataset, load_metric
from datasets import DatasetDict, Dataset
import random
import pandas as pd
random.seed(42)

jnlpba = load_dataset('jnlpba', split=['train', "validation"])
jnlpba = DatasetDict({"train": jnlpba[0], "validation": jnlpba[1]})

class JnlpbDataset():
    def __init__(self, dataset, portion, type_path):
        self.dataset = dataset[type_path]
        self.portion = portion
        self.merge()
        self.apply()
        
    def map_tags(self, row):
        mapping = {
            0: "O",
            1: "B-DNA",
            2: "I-DNA",
            3: "B-RNA",
            4: "I-RNA",
            5: "B-cell_line",
            6: "I-cell_line",
            7: "B-cell_type",
            8: "I-cell_type",
            9: "B-protein",
            10: "I-protein"
        }
        row['ner_tags'] = [[mapping[tag] for tag in row['ner_tags']]][0]
        return row        

    def merge_tags(self, tags, tokens):
        #todo test if this works also in the scenario of having two B- tags side by side
        merged_tags = []
        merged_tokens = []
        i = 0
        while i < len(tags):
            if tags[i].startswith('B-'):
                merged_tag = tags[i][2:]
                merged_token = tokens[i]
                i += 1
                while i < len(tags) and tags[i].startswith('I-'):
                    merged_tag += ' ' + tags[i][2:]
                    merged_token += ' ' + tokens[i]
                    i += 1
                merged_tags.append(merged_tag)
                merged_tokens.append(merged_token)
            else:
                merged_tags.append(tags[i])
                merged_tokens.append(tokens[i])
                i += 1
        for i in range(len(merged_tags)):            
            s = merged_tags[i].split()[0]
            s = s[0].upper() + s[1:]
            merged_tags[i] = s
        return merged_tags, merged_tokens

    def merge(self):
        df_train = pd.DataFrame(self.dataset)
        df_train = df_train.apply(self.map_tags, axis=1)
        df_train[['ner_tags', 'tokens']] = df_train.apply(lambda x: self.merge_tags(x['ner_tags'], x['tokens']), axis=1, result_type='expand')
        #print(df_train)
        self.dataset = Dataset.from_pandas(df_train)
        
    def missing(self, row):
        #print(len(self.label_list))
        lst = row["ner_tags"]
        #[1 2 0 3]
        #[1 0 0 3]
        if any(x != 0 for x in lst):
            index = random.choice([i for i, x in enumerate(lst) if x != 0])
            #print("missing:")
            #print(row["ner_tags"])
            lst[index] = 0
            row["ner_tags"] = lst
            #print(row["ner_tags"])
            #print(30*"-")
            return row
        else:
            return row

    def wrong(self, row, num_tags):
        lst = row["ner_tags"]
        tags = []
        #it would be nice to have a debugger who can display me the values of the vars
        for i in range(1,num_tags):
            tags.append(i)
        if any(x != 0 for x in lst):
            #print(30*"-")
            #print("ner_tags:")
            #print(row["ner_tags"])    
            indices = [i for i, x in enumerate(lst) if x != 0]
            #print(row["ner_tags"])    
            #print("indices:")
            #print(indices)
            random_index = random.choice(indices)
            #print(row["ner_tags"])    
            #print("random index:")
            #print(random_index)
            #[1 2 0 3]
            #[1 2 0 4]
            current_value = lst[random_index]
            #print(row["ner_tags"])    
            #print("current value:")
            #print(current_value)
            random_number = random.choice([x for x in [1, 2, 3, 4, 5] if x != current_value])
            #print(row["ner_tags"])    
            #print("random_number:")
            #print(random_number)
            lst[random_index] = random_number
            #print("wrong:")
            #print(row["ner_tags"])
            row["ner_tags"] = lst
            #print(row["ner_tags"])
            #print("ner_tags:")
            #print(row["ner_tags"])
            #print(30*"-")
            #thats so we
            return row
        else:
            return row
                        
    def uncomplete(self):
        #todo should i implement this
        pass

    def apply(self):
        #shuffled_data = self.dataset.shuffle()
        num_portion = int(len(self.dataset) * self.portion / 100)
        df = self.dataset.to_pandas() 
        tags = [tag for row in df['ner_tags'] for tag in row]
        unique_tags = set(tags)
        mapping = {'O': 0, 'RNA': 1, 'DNA': 2, 'Cell_line': 3, 'Cell_type': 4, 'Protein': 5}

        #for index, item in enumerate(unique_tags):
         #   mapping[item] = index        
        #iter over df ner tags column and set each string to number from mapping
        df['ner_tags'] = [[mapping[tag] for tag in tags] for tags in df['ner_tags']]    
        #print(mapping)
        #print(df["ner_tags"])
        #i input a certain portion but i get the same results no matter if the portion is 20, 40 or what so ever. 
        for i in range(num_portion):
            random_number = random.randint(1, 2)
            if random_number == 1:
                new_row = self.missing(df.iloc[i])
                df.iloc[i] = new_row
            elif random_number == 2:
                num_tags = len(unique_tags)
                new_row = self.wrong(df.iloc[i], num_tags)
                df.iloc[i] = new_row
            '''else:
                self.uncomplete()'''
        self.dataset = Dataset.from_pandas(df)
        
    def get_dataset(self):
        return self.dataset


input_dataset_train = JnlpbDataset(dataset=jnlpba, portion=50, type_path='train')
dataset_train = input_dataset_train.get_dataset()


input_dataset_validation = JnlpbDataset(dataset=jnlpba, portion=0, type_path='validation')
dataset_validation = input_dataset_validation.get_dataset()

datasets = DatasetDict({"train": dataset_train, "validation": dataset_validation})


Generating train split:   0%|          | 0/37094 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/7714 [00:00<?, ? examples/s]

Dataset jnlpba downloaded and prepared to /root/.cache/huggingface/datasets/jnlpba/jnlpba/1.0.0/3062f220823930cffde7976b694aa67bac3b06c322a02ced92d3761519810ce4. Subsequent calls will reuse this data.


  0%|          | 0/2 [00:00<?, ?it/s]

In [7]:
df = dataset_train.to_pandas()
label_list = list(set([tag for row in df['ner_tags'] for tag in row]))

In [8]:
from transformers import AutoTokenizer
    
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/213k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/436k [00:00<?, ?B/s]

In [9]:
import transformers
assert isinstance(tokenizer, transformers.PreTrainedTokenizerFast)

In [10]:
label_all_tokens = True

In [11]:
def tokenize_and_align_labels(examples):
    tokenized_inputs = tokenizer(examples["tokens"], truncation=True, is_split_into_words=True)

    labels = []
    for i, label in enumerate(examples[f"{task}_tags"]):
        word_ids = tokenized_inputs.word_ids(batch_index=i)
        previous_word_idx = None
        label_ids = []
        for word_idx in word_ids:
            # Special tokens have a word id that is None. We set the label to -100 so they are automatically
            # ignored in the loss function.
            if word_idx is None:
                label_ids.append(-100)
            # We set the label for the first token of each word.
            elif word_idx != previous_word_idx:
                label_ids.append(label[word_idx])
            # For the other tokens in a word, we set the label to either the current label or -100, depending on
            # the label_all_tokens flag.
            else:
                label_ids.append(label[word_idx] if label_all_tokens else -100)
            previous_word_idx = word_idx

        labels.append(label_ids)

    tokenized_inputs["labels"] = labels
    return tokenized_inputs

In [12]:
tokenized_datasets = datasets.map(tokenize_and_align_labels, batched=True)

  0%|          | 0/38 [00:00<?, ?ba/s]

  0%|          | 0/8 [00:00<?, ?ba/s]

In [13]:
from transformers import AutoModelForTokenClassification, TrainingArguments, Trainer

model = AutoModelForTokenClassification.from_pretrained(model_checkpoint, num_labels=len(label_list))

Downloading:   0%|          | 0.00/436M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-cased were not used when initializing BertForTokenClassification: ['cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForTokenClassification were not initialized from the model checkpoint at bert-base-cas

In [14]:
model_name = model_checkpoint.split("/")[-1]
args = TrainingArguments(
    f"{model_name}-{task}-jnlpba-weak-labelled",
    evaluation_strategy = "steps",
    eval_steps = 50,
    learning_rate=2e-5,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    num_train_epochs=1,
    weight_decay=0.01,
    report_to="wandb",
    #push_to_hub=True,          
    #todo hide token 
    #push_to_hub_token="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"
)

In [15]:
from transformers import DataCollatorForTokenClassification

data_collator = DataCollatorForTokenClassification(tokenizer)

In [16]:
#metric = load_metric("seqeval")

In [17]:
'''import numpy as np

def compute_metrics(p):
    predictions, labels = p
    predictions = np.argmax(predictions, axis=2)

    # Remove ignored index (special tokens)
    true_predictions = [
        [label_list[p] for (p, l) in zip(prediction, label) if l != -100]
        for prediction, label in zip(predictions, labels)
    ]
    true_labels = [
        [label_list[l] for (p, l) in zip(prediction, label) if l != -100]
        for prediction, label in zip(predictions, labels)
    ]
    
    results = metric.compute(predictions=true_predictions, references=true_labels)
    return {
        "precision": results["overall_precision"],
        "recall": results["overall_recall"],
        "f1": results["overall_f1"],
        "accuracy": results["overall_accuracy"],
    }'''

'import numpy as np\n\ndef compute_metrics(p):\n    predictions, labels = p\n    predictions = np.argmax(predictions, axis=2)\n\n    # Remove ignored index (special tokens)\n    true_predictions = [\n        [label_list[p] for (p, l) in zip(prediction, label) if l != -100]\n        for prediction, label in zip(predictions, labels)\n    ]\n    true_labels = [\n        [label_list[l] for (p, l) in zip(prediction, label) if l != -100]\n        for prediction, label in zip(predictions, labels)\n    ]\n    \n    results = metric.compute(predictions=true_predictions, references=true_labels)\n    return {\n        "precision": results["overall_precision"],\n        "recall": results["overall_recall"],\n        "f1": results["overall_f1"],\n        "accuracy": results["overall_accuracy"],\n    }'

In [18]:
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import accuracy_score
import numpy as np
def custom_compute_metrics(p):
  predictions, labels = p
  predictions = np.argmax(predictions, axis=2)

  true_predictions = [
        [label_list[p] for (p, l) in zip(prediction, label) if l != -100]
        for prediction, label in zip(predictions, labels)
    ]

  true_labels = [
        [label_list[l] for (p, l) in zip(prediction, label) if l != -100]
        for prediction, label in zip(predictions, labels)
    ]

  true_predictions = np.array([item for sublist in true_predictions for item in sublist])

  true_labels = np.array([item for sublist in true_labels for item in sublist])
  accuracy = accuracy_score(true_labels, true_predictions)
  precision, recall, fscore, support = precision_recall_fscore_support(true_labels, true_predictions, zero_division=1, average="weighted")
  return {'precision': precision, 'recall': recall, 'f1': fscore,'accuracy':accuracy, 'support': support}

In [19]:
trainer = Trainer(
    model,
    args=args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    data_collator=data_collator,
    tokenizer=tokenizer,
    compute_metrics=custom_compute_metrics
)

In [ ]:
trainer.train()

The following columns in the training set don't have a corresponding argument in `BertForTokenClassification.forward` and have been ignored: id, ner_tags, tokens. If id, ner_tags, tokens are not expected by `BertForTokenClassification.forward`,  you can safely ignore this message.
/usr/local/lib/python3.8/dist-packages/transformers/optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
***** Running training *****
  Num examples = 37094
  Num Epochs = 1
  Instantaneous batch size per device = 16
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 1
  Total optimization steps = 2319
  Number of trainable parameters = 107724294
Automatic Weights & Biases logging enabled, to disable set os.environ["WANDB_DISABLED"] = "true"
You're using a B

The following columns in the evaluation set don't have a corresponding argument in `BertForTokenClassification.forward` and have been ignored: id, ner_tags, tokens. If id, ner_tags, tokens are not expected by `BertForTokenClassification.forward`,  you can safely ignore this message.
***** Running Evaluation *****
  Num examples = 7714
  Batch size = 16
The following columns in the evaluation set don't have a corresponding argument in `BertForTokenClassification.forward` and have been ignored: id, ner_tags, tokens. If id, ner_tags, tokens are not expected by `BertForTokenClassification.forward`,  you can safely ignore this message.
***** Running Evaluation *****
  Num examples = 7714
  Batch size = 16
The following columns in the evaluation set don't have a corresponding argument in `BertForTokenClassification.forward` and have been ignored: id, ner_tags, tokens. If id, ner_tags, tokens are not expected by `BertForTokenClassification.forward`,  you can safely ignore this message.
***** 

The following columns in the evaluation set don't have a corresponding argument in `BertForTokenClassification.forward` and have been ignored: id, ner_tags, tokens. If id, ner_tags, tokens are not expected by `BertForTokenClassification.forward`,  you can safely ignore this message.
***** Running Evaluation *****
  Num examples = 7714
  Batch size = 16
The following columns in the evaluation set don't have a corresponding argument in `BertForTokenClassification.forward` and have been ignored: id, ner_tags, tokens. If id, ner_tags, tokens are not expected by `BertForTokenClassification.forward`,  you can safely ignore this message.
***** Running Evaluation *****
  Num examples = 7714
  Batch size = 16
Saving model checkpoint to bert-base-cased-ner-jnlpba-weak-labelled/checkpoint-500
Configuration saved in bert-base-cased-ner-jnlpba-weak-labelled/checkpoint-500/config.json
Model weights saved in bert-base-cased-ner-jnlpba-weak-labelled/checkpoint-500/pytorch_model.bin
tokenizer config fi

In [ ]:
trainer.evaluate()

In [ ]:
'''predictions, labels, _ = trainer.predict(tokenized_datasets["validation"])
predictions = np.argmax(predictions, axis=2)

# Remove ignored index (special tokens)
true_predictions = [
    [label_list[p] for (p, l) in zip(prediction, label) if l != -100]
    for prediction, label in zip(predictions, labels)
]

true_labels = [
    [label_list[l] for (p, l) in zip(prediction, label) if l != -100]
    for prediction, label in zip(predictions, labels)
]

results = metric.compute(predictions=true_predictions, references=true_labels)
results'''

In [ ]:
'''from sklearn.metrics import precision_recall_fscore_support
import numpy as np

#mapping = {0:"A", 1:"B", 2:"C", 3:"D"}

#Flatten the lists of predictions and true labels 
true_predictions = np.array([item for sublist in true_predictions for item in sublist])

true_labels = np.array([item for sublist in true_labels for item in sublist])

precision, recall, fscore, support = precision_recall_fscore_support(true_labels, true_predictions, zero_division=1)

metrics_dict = {"precision":precision,"recall":recall,"fscore":fscore}

#wandb.log(metrics_dict)
wandb.run.summary["precision"] = precision
wandb.run.summary["recall"] = recall
wandb.run.summary["fscore"] = fscore'''

In [ ]:
wandb.finish()

In [ ]:
#trainer.push_to_hub()